### PR TITLE
Merge pull request #1 from raviraj-12/TS-1

### PR DESCRIPTION
**Pull request by raviraj-12**
Successfully merging this pull request may close these issues.

### CODE REVIEW

**Comment by raviraj-12** [comment]
not added MYSQL information

**Comment by raviraj-12** [comment]
now added MYSQL info .please check

**Comment by raviraj-12** [comment]
Everything is OK plase review the code and merge

**Comment by ravirajgundgole** [comment]
ok i will be merging the code

**Review by ravirajgundgole — COMMENTED** [review]
Raviraj Dilip Gundgole adde dthe revicew

**Comment by raviraj-12** [comment]
finally merge the code

**Pull request merged**
